### ISSUE TITLE
Hat Description to Reflect Stats

### ISSUE THREAD

**Issue by Daylight-V** [domsim1/stardew-valley-deluxe-hats-mod#9]
I'm currently playing on a server with 150+ SMAPI mods that my partner and I hand picked. If allowed I may even release the bundle of mods somewhere for people too lazy to search but who want a fresh Stardew experience. Haven't decided on that yet as I don't want to anger any mod creators.

I would love to add your hat mod but I have 2 issues with it.

1) Is there any way to change the hat descriptions to include the stats given. So we don't need to lookup the stats online? I don't want to add mods that add hassle to the gaming experience and this includes mods that are not straight forward.

Even if you think editing descriptions are not necessary any pointing in the right direction to implement them myself would be welcome :)

2) The hats are too OP. My brother and I, one bop enemies in the cave after receiving the squire helmet and we take only 1 damage from any attack. Having 0 room to grow makes the game dull and boring.

I make games in unity as a hobby so I downloaded the repository and I can edit the hat files using visual studio and I can nerf the hats I think are too OP to personal preference so number 2. I noticed that in the finished mod download from nexus mods there are no hat files to edit compared to the folder on git hub, how do you go from folder with hat files to finished mod folder which only contains 3 files (dll, PDB, JSON)?

Kind Regards,
Daylight.

Ps. Your mod is awesome :)

**Comment by domsim1** [comment]
Hi @Daylight-V ,
Thank you for trying the mod and the feedback about balancing. 
Version 1.0.4 that will be realised soon will be adding the effects to the descriptions of the hats, thanks to your suggestion! 😃

About the too OP hats, this is not my intention. I would be more than happy to connect with you over a call (on discord or something) to help you get started with contributing to the mod so you can help balance some hats and maybe even implement some hat effects. What do you think?

> how do you go from folder with hat files to finished mod folder which only contains 3 files (dll, PDB, JSON)?

When you compile the code with the visual studio it will package all the code into the one DLL file. You can do this by pressing start on visual studio, it will build the mod, install it and run Stardew Valley.
